### ISSUE TITLE
Upgrade to gatsby-transformer-yaml v4 broke tag page images

### ISSUE THREAD

**Issue by ScottG489** [scttcper/gatsby-casper#115]
Tags can specify images for their pages. This is demonstrated here:
https://github.com/scttcper/gatsby-casper/blob/master/src/content/tag.yaml
```yaml
- id: speeches
  description: Some of the greatest words ever spoken.
  image: img/speeches-cover.jpg
```

However, if you view the demo you can see that the background image is not displaying:
https://gatsby-casper.netlify.app/tags/speeches/

This is due to `id` being a reserved internal keyword for Gatsby, so it's translated to `yamlId`. See here:
https://www.gatsbyjs.com/plugins/gatsby-transformer-yaml/#id-and-yamlid-key

This is the breaking change in the plugin for more info:
https://github.com/gatsbyjs/gatsby/pull/28943

It's been broken in this repo since the upgrade to Gatsby v4 in this commit:
910bbd24ae86e38f14513c84a5cdf4041f97fdd9

Solution to this might be to change all the `id` references to `yamlId`. However, I think a better approach might be to use a different name in the yaml instead of `id` such as `name` or something.

I think this only affects tags since I believe the only other yaml file is `authors.yaml` and that doesn't appear to use `id`, but I haven't investigated deeply.

Either way, the references would need to be updated in the code:
https://github.com/scttcper/gatsby-casper/blob/master/src/templates/tags.tsx#L37
https://github.com/scttcper/gatsby-casper/blob/master/src/templates/tags.tsx#L55

and the graphQL query:
https://github.com/scttcper/gatsby-casper/blob/master/src/templates/tags.tsx#L130

**Comment by scttcper** [comment]
yeah should probably be renamed, makes sense
