### ISSUE TITLE
how to limit posts on home page ?  

### ISSUE THREAD

**Issue by NKaushik89** [scttcper/gatsby-casper#27]
Can we limit post counts on home page ? Currently if I have a total 30 posts, all are showing. I need to show 10 posts with a page number buttons below.

**Comment by scttcper** [comment]
https://github.com/scttcper/gatsby-casper/blob/master/src/pages/index.tsx#L193

**Comment by polc** [comment]
hey @scttcper, thanks for building this nice theme! For the moment there is no build-in pagination, right?

**Comment by scttcper** [comment]
@polc nope
