### ISSUE TITLE
Author Issues

### ISSUE THREAD

**Issue by ccapasso01** [scttcper/gatsby-casper#31]
I am trying to add an author and it isn't working.  When I am in dev, the site errors out. When I try a build, I get an error that it can't find the id.  

I've even tried just modifying the existing Author name from Ghost to Chris and then modifying an existing .md file Author from Ghost to Chris.  This too fails.

**Comment by Baadier-Sydow** [comment]
This is kinda weird but I had the exact same issue. It sorta felt like a caching issue cause I could only resolve it by setting all the posts to have author ghost and then change it back to my author one by one.

When I debugged it the author id would always come back as null but everything appeared to be correctly set.

**Comment by ccapasso01** [comment]
I was able to get it resolved by deleting both cache and public folder. After that, I could build/develop and it works.

The only other issue I have is if you remove all authors but yourself and you have an empty field in your author file. For example, if you don’t have a profile image or you don’t have a website, then the build fails.




On Sun, Feb 17, 2019 at 5:50 AM -0500, "Baadier Sydow" <notifications@github.com<mailto:notifications@github.com>> wrote:


This is kinda weird but I had the exact same issue. It sorta felt like a caching issue cause I could only resolve it by setting all the posts to have author ghost and then change it back to my author one by one.

When I debugged it the author id would always come back as null but everything appeared to be correctly set.

**Comment by iColdPlayer** [comment]
Hi, I had the same issue here.
I had followed @ccapasso01 suggestion but it doesn't work.
still trying with another different way to get it done.

**Comment by JoeTrubenstein** [comment]
I was able to get around this only by leaving the default "Ghost" and "Another Author" in place.

I then added my own authors below these two in the author.yaml file, and they now work as intended.

**Comment by JoeTrubenstein** [comment]
I was able to get around this only by leaving both "Ghost" and "Another Author" in place.

I then added my own authors below these two in the author.yaml file, and they now work as intended.
