### ISSUE TITLE
Drafts show up in the ReadNextFeed

### ISSUE THREAD

**Issue by FarazPatankar** [scttcper/gatsby-casper#33]
The title is kind of self-explanatory. Currently, even if I set draft to true for a post, it still shows up in the `ReadNextFeed` section of the page. Is there a quick way to get around this?

**Comment by scttcper** [comment]
this should be filtered here https://github.com/scttcper/gatsby-casper/blob/0e82d02da6a0e8eb733f1336664648b34cea35ca/src/templates/post.tsx#L373

**Comment by FarazPatankar** [comment]
That's what I thought as well but I don't think it does. I believe that particular fetch is for this bit (314-316):
https://github.com/scttcper/gatsby-casper/blob/0e82d02da6a0e8eb733f1336664648b34cea35ca/src/templates/post.tsx#L314

But the issue actually is in lines 318 and 319 where we use the `PageContext` interface defined on line 179.
https://github.com/scttcper/gatsby-casper/blob/0e82d02da6a0e8eb733f1336664648b34cea35ca/src/templates/post.tsx#L179

Is there any way we could apply the same filter over there?

**Comment by scttcper** [comment]
need a way to find the next non-draft post https://github.com/scttcper/gatsby-casper/blob/master/gatsby-node.js#L115

**Comment by scttcper** [comment]
i think they're all filtered now in https://github.com/scttcper/gatsby-casper/commit/0ed1df81c6691d4237149cd0668d79a60f63a470

**Comment by FarazPatankar** [comment]
I think we can close the issue as the commit you made seems to have fixed it.
