### ISSUE TITLE
Consider converting to a theme?

### ISSUE THREAD

**Issue by chadly** [scttcper/gatsby-casper#37]
[Gatsby Themes](https://www.gatsbyjs.org/blog/tags/themes) are still pre-release, but I think this would work really nice as a theme rather than a starter. I think in an ideal world, most of the project here would be encapsulated in a theme. Then you could have a separate starter that uses the theme with the example `content` folder.

**Comment by TomaszWaszczyk** [comment]
What is the difference between theme and the starter?

**Comment by chadly** [comment]
@TomaszWaszczyk here is a [good intro to themes](https://www.gatsbyjs.org/blog/2019-01-31-why-themes/) if you aren't familiar

The themes feature was just [announced as stable today](https://www.gatsbyjs.org/blog/2019-07-03-announcing-stable-release-gatsby-themes/).

**Comment by chadly** [comment]
There is also some good docs now on how to [convert a starter to a theme](https://www.gatsbyjs.org/docs/themes/converting-a-starter/).

**Comment by scttcper** [comment]
I finished creating the MVP of how this would look as a theme. You can check it out here https://github.com/scttcper/gatsby-theme-casper

https://github.com/scttcper/gatsby-theme-casper-example serves as an example of how it would be used.

The gatsby theme contest they have going on finally motivated me https://themejam.gatsbyjs.org/rules
