### ISSUE TITLE
Not pulling my content (from local install) - just seeing the starter content

### ISSUE THREAD

**Issue by acollien** [scttcper/gatsby-casper#38]
I moved from the ghost official gatsby stater repo (all worked fine with netlify and my custom domain etc.)

With is one, I can't seem to get it to display my content. I updated the siteMetadata section with my url. Netlify is setup correctly - webhook rebuilds are successful without errors.

With the ghost gatsby starter, I had to add my content api in the package.json file, but I can't see/find an equivalent in this repo? is this my issue? Or what/where do I need to edit to pull content from my db instead of using the repo default content?

**Comment by scttcper** [comment]
This starter does not integrate with ghost currently.

**Comment by acollien** [comment]
Well, that explains my issues. Hope it's on the road map?

**Comment by badrihippo** [comment]
@scttcper if I managed to implement Ghost integration, would you be open to merging it in?

**Comment by scttcper** [comment]
The point of this repo is that you don't need ghost and I think once you have ghost, you'll notice other shortcomings of the starter. However, it does seem super useful... Ghost is an excellent product. Is there any way to use ghost with a flag or something? @badrihippo

**Comment by badrihippo** [comment]
After playing round a bit, I realised adding Ghost is not as straightforward as I thought. It might be possible to use it with a flag if we adjust some of the data structure to match. I'm still figuring it out (first time I'm using Gatsby!), but I'll let you know if I come up with something
