### ISSUE TITLE
Request - Social Sharing

### ISSUE THREAD

**Issue by ccapasso01** [scttcper/gatsby-casper#39]
Hi @scttcper 

Firstoff, thank you for your work on this.  I've been building my blog using this and am just about ready to go live.  

Before I do so though, I was really hoping to use some sort of "Share on Social" plugin/function.  

Do you have any plans to add something or have any suggestions for what to add?

**Comment by scttcper** [comment]
@ccapasso01 hey there isn't any plans for new features that casper itself isn't adding keeping this the same as https://github.com/TryGhost/Casper
