### ISSUE TITLE
Issue with ReadNextCardStyleProps

### ISSUE THREAD

**Issue by ohalliday** [scttcper/gatsby-casper#43]
Hi there, I'm getting the error

{
	"resource": "/c:/Users/owenm/Desktop/blog_casper/src/components/ReadNextCard.tsx",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type '(props: ReadNextCardStylesProps) => string' is not assignable to parameter of type 'Interpolation<Pick<DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>, \"color\" | \"hidden\" | \"style\" | \"defaultChecked\" | \"defaultValue\" | \"suppressContentEditableWarning\" | ... 247 more ... | \"css\"> & { ...; }>'.\n  Type '(props: ReadNextCardStylesProps) => string' is not assignable to type 'FunctionInterpolation<Pick<DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>, \"color\" | \"hidden\" | \"style\" | \"defaultChecked\" | \"defaultValue\" | \"suppressContentEditableWarning\" | ... 247 more ... | \"css\"> & { ...; }>'.\n    Types of parameters 'props' and 'mergedProps' are incompatible.\n      Property 'coverImage' is missing in type 'Pick<DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>, \"color\" | \"hidden\" | \"style\" | \"defaultChecked\" | \"defaultValue\" | \"suppressContentEditableWarning\" | ... 247 more ... | \"css\"> & { ...; }' but required in type 'ReadNextCardStylesProps'.",
	"source": "ts",
	"startLineNumber": 27,
	"startColumn": 27,
	"endLineNumber": 27,
	"endColumn": 79,
	"relatedInformation": [
		{
			"startLineNumber": 11,
			"startColumn": 3,
			"endLineNumber": 11,
			"endColumn": 13,
			"message": "'coverImage' is declared here.",
			"resource": "/c:/Users/owenm/Desktop/blog_casper/src/components/ReadNextCard.tsx"
		},
		{
			"startLineNumber": 27,
			"startColumn": 27,
			"endLineNumber": 27,
			"endColumn": 79,
			"message": "Did you mean to call this expression?",
			"resource": "/c:/Users/owenm/Desktop/blog_casper/src/components/ReadNextCard.tsx"
		}
	]
}

**Comment by scttcper** [comment]
see the above commit for a fix
