### ISSUE TITLE
No pagination included in the theme

### ISSUE THREAD

**Issue by m-czernek** [scttcper/gatsby-casper#47]
The theme does not have any form of pagination of its index page. Without pagination, the theme is not entirely user friendly.

**Comment by m-czernek** [comment]
I have added basic pagination to my blog. @scttcper would you be interested in me comitting the code?

You can check it out at https://github.com/m-czernek/halfastack-src/pull/1

**Comment by scttcper** [comment]
yeah i'd be interested in a PR

**Comment by m-czernek** [comment]
Provided.
