### ISSUE TITLE
Dev watch fails when markdown files are edited

### ISSUE THREAD

**Issue by Tumetsu** [scttcper/gatsby-casper#50]
I'm having an issue with this starter. Just after starting the project with 
`gatsby new gatsby-casper https://github.com/scttcper/gatsby-casper`
and running `npm run dev` when I go and edit any markdown files in the content directory, the dev process will spit out the following error:

```
ERROR 

[ { TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
      at validateString (internal/validators.js:125:11)
      at Object.resolve (path.js:1080:7)
      at findLinkedFileNode (/home/tuomas/Code/gatsby-casper/node_modules/gatsby/dist/schema/resolvers.js:207:47)
      at resolveValue (/home/tuomas/Code/gatsby-casper/node_modules/gatsby/dist/schema/resolvers.js:222:108)
      at /home/tuomas/Code/gatsby-casper/node_modules/gatsby/dist/schema/resolvers.js:219:10
      at process._tickCallback (internal/process/next_tick.js:68:7)
    message:
     'The "path" argument must be of type string. Received type undefined',
    locations: [ [Object] ],
    path:
     [ 'allMarkdownRemark', 'edges', 1, 'node', 'frontmatter', 'image' ] } ]


 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

The "path" argument must be of type string. Received type undefined

GraphQL request:17:15
16 |               draft
17 |               image {
   |               ^
18 |                 childImageSharp {



  Error: The "path" argument must be of type string. Received type undefined
  GraphQL request:17:15
  16 |               draft
  17 |               image {
     |               ^
  18 |                 childImageSharp {
  
  - gatsby-node.js:108 Object.exports.createPages
    /home/tuomas/Code/gatsby-casper/gatsby-node.js:108:11
```
Looks like something is off with the graphql query in the `gatsby-node.js` with `                childImageSharp` ? However since this is my first project with Gatsby/Graphql I have no idea yet what is the root cause here.

If I rerun the `npm run dev` it will build fine but this is very annoying when editing the posts.

**Comment by Tumetsu** [comment]
I did  some more debugging and it looks like in the `resolvers.js` there is occasionally a wrong data type. The `parentFileNode` is on dev's watch the following object:
```
{ title: 'Great Gatsby',
  author: 'Another Author',
  tags: [],
  image: 'img/marvin-meyer-794521-unsplash.jpg',
  date: '1922-12-12T10:00:00.000Z',
  draft: false }
``` 
Which then causes an error since the resolver expects the `parentFileNode` to contain `dir` property.

**Comment by scttcper** [comment]
Thanks for looking into it. I also looked a little and couldn't figure it out. Downgrading the dependencies fixed it. I've pushed the revert to master if you want to copy/paste the package.json or whatever

**Comment by Tumetsu** [comment]
Thanks, that seemed to do the trick. If I have time I might try to track down the exact culprit dependency  but this will do for now :+1:
