### ISSUE TITLE
How to use unsplash image for post featuredImage?

### ISSUE THREAD

**Issue by xiyizhou** [scttcper/gatsby-casper#51]
Hi @scttcper

thank you for your work on this.

How to use unsplash image for post featuredImage?

is it only support local image?

**Comment by scttcper** [comment]
@xiyizhou right yeah. At the moment you would need to download the image and then use it.

**Comment by xiyizhou** [comment]
Do you have any plans to support unsplash?

**Comment by xiyizhou** [comment]
> @xiyizhou right yeah. At the moment you would need to download the image and then use it.

Do you have any plans to support unsplash?

**Comment by scttcper** [comment]
Right now the images use [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/) which relies on files to enhance the image loading experience many are used to in gatsby based static websites. I think all ghost does is download the image for you in the same way it provides a markdown editor to work in I don't think this will be supported.

**Comment by xiyizhou** [comment]
> Right now the images use [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/) which relies on files to enhance the image loading experience many are used to in gatsby based static websites. I think all ghost does is download the image for you in the same way it provides a markdown editor for you to work in. I don't think this will be supported.

thank you for your job, have a good day
