### ISSUE TITLE
Laggy scrolling on high resolution screens

### ISSUE THREAD

**Issue by samleez** [scttcper/gatsby-casper#57]
Hi there,

First of all, I want to say that this starter is one of the best starters of gatsby out there, with that being said there are some issues I encounter from the first use:

1- **The scrolling** is not smooth and feels like the theme is going to crash or freeze which gives a totally uncomfortable user experience, I found out the issue is originated from Casper `https://github.com/TryGhost/Casper`

2- **The animations** of the posts containers, every time I experienced a delay when I move over with the mouse.

3- **Performance Audit** I have been doing a lot of audits on this starter and the main issue I found is the images, for some reason all the tools I have used state that the theme needs to serve scaled images.

Hope I will get some useful insights here
@scttcper

**Comment by samleez** [comment]
Here's the same issue from the default theme for Ghost Casper
`https://github.com/TryGhost/Casper/issues/658`

**Comment by samleez** [comment]
Anyone have noticed this issue?

**Comment by samleez** [comment]
@scttcper I can pay you for your time if you get this fix as soon as possible

**Comment by scttcper** [comment]
Laggy scrolling where? On the blog page? How many images? Are you using a production build? Does the demo lag when scrolling? What browser?

**Comment by samleez** [comment]
> Laggy scrolling where? On the blog page? How many images? Are you using a production build? Does the demo lag when scrolling? What browser?

Well first of all the issue is has to do with Casper
see the same issue here:
`https://github.com/TryGhost/Casper/issues/658
`

- Laggy scrolling on all pages.
- The image issue I can handle it.
- Yes, I used developed build and production build and the issue remains.
- Tested on chrome both pc and android.
- The starter seems to work fine in opera with no scrolling lag.

**Comment by samleez** [comment]
@scttcper 

Also, I have noticed when resizing the browser to a small window it starts scrolling smoothly

**Comment by scttcper** [comment]
It most likely has to do with how they're doing the flow of the page and how intense it is on the gpu, there's pretty intense css. When the page shrinks it changes to the alternate layout declared here https://github.com/scttcper/gatsby-casper/blob/master/src/templates/index.tsx#L28 Could try using that as your page flow by default.

**Comment by samleez** [comment]
@scttcper sorry scott but I can't figure out where to put that value as using my page flow by default. is it in the same file? Index.tsx

**Comment by scttcper** [comment]
easiest way to try it is to change `@media (min-width: 795px)` to a larger size that triggers it. Or overwrite the styles for .post-card which are in another file

**Comment by samleez** [comment]
> easiest way to try it is to change `@media (min-width: 795px)` to a larger size that triggers it. Or overwrite the styles for .post-card which are in another file

It worked great when I changed to `@media (min-width: 2000px)` i tried 960px and 1440 px but only 2000px worked

**Comment by scttcper** [comment]
its whatever your screen size is. can just remove the @media query and have it on all the time

**Comment by samleez** [comment]
Hi again @scttcper seems like the issue remains... but  I found out that` background-size:cover` has terrible performance and this starter uses a lot of this so I removed it and resized and compress the pictures but the lag is still there in high-resolution screens.

It only happens on a high-resolution screen I have tested the starter on 8 different screens and the issue arises only on bigger screens.

**Comment by samleez** [comment]
Seems like it's an issue that related to the browser... the starter works just fine in firefox quantum, brave, and Google Chrome canary Version 80.0.3970.0 (Official Build).

**Comment by samleez** [comment]
Hi @scttcper 

The issue has been fixed in Casper, it has to do with subscribe from overlay class, I tried to fix it by myself in this starter but with no luck

can you please take a look at this fix and merge it to this starter:
https://github.com/TryGhost/Casper/issues/658#issuecomment-557715167

**Comment by samleez** [comment]
**The issue has been fixed**

just delete the following line:

https://github.com/scttcper/gatsby-casper/blob/66bd50cb4a8f9b902751de9cabdff9d0a5be8a63/src/components/subscribe/SubscribeOverlay.tsx#L27

Apparently backdrop-filter: blur(3px); is heavy on most browsers. Removing it will remove the lag.

**Comment by scttcper** [comment]
v3 doesn't have the backdrop filter
