### ISSUE TITLE
Favicon not loading, not being copied from source

### ISSUE THREAD

**Issue by JLShrago** [scttcper/gatsby-casper#9]
I can't for the life of me get the compiled site to display a favicon.

**Comment by tony-ho** [comment]
I had the same issue.

The easiest solution, and the one I used, was to move the favicon to a top-level `static` folder (ie. alongside `src`).

More information, and an alternative solution, can be found here:
https://github.com/gatsbyjs/gatsby/issues/2987

**Comment by JLShrago** [comment]
Thanks Tony. Adding to src is fine except locally but it's not added to src on production. Best solution is to import it into:
pages/about.tsx
templates/author.tsx
templates/post.tsx
templates/tags.tsx

**Comment by geocine** [comment]
For anyone who is trying to figure this out on your `layouts > index.tsx` do this
```tsx
// @ts-ignore
import favicon from '../../src/favicon.ico';

const IndexLayout: React.FunctionComponent<IndexProps> = props => {
  return <div className={props.className}>
    <Helmet>
      <link rel="icon" href={favicon} type="image/x-icon" />
    </Helmet>
    {props.children}
  </div>;
};

export default IndexLayout;
```
